### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by DimitryW**
吳佳俞
彭彭老師，我先交作業審核，再想想可以怎麼優化頁面
謝謝!
http://3.230.236.135:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
Remove booking data after successful ordering.

**Comment by cwpeng** [comment]
I see no changes. If you do think you have fixed it, just let me know.

**Comment by DimitryW** [comment]
吳佳俞
http://3.230.236.135:3000/

yes, confirm fixed it. kindly check again, thank you.
image

**Comment by cwpeng** [comment]
Back to booking page and check after ordering.

**Comment by DimitryW** [comment]
吳佳俞
I got it!  I've removed booking data from booking page.
http://3.230.236.135:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
