### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by DimitryW**
吳佳俞
http://3.230.236.135:3000/api/attractions?page=1
http://3.230.236.135:3000/api/attractions?page=0&keyword=藝術
http://3.230.236.135:3000/api/attraction/100

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK. But, we should use second argument of mycursor.execute() to add variable data to SQL query. It's the best practice to help prevent SQL Injection attack.

Fix issue and request me review again.

**Comment by DimitryW** [comment]
吳佳俞，已經修改好 mycursor.execute() 的部分
http://3.230.236.135:3000/api/attractions?page=1
[http://3.230.236.135:3000/api/attractions?page=0&keyword=藝術](http://3.230.236.135:3000/api/attractions?page=0&keyword=%E8%97%9D%E8%A1%93)
http://3.230.236.135:3000/api/attraction/100

**Comment by cwpeng** [comment]
You can just leave comment and request me review again in the same pull request, so we can trace the conversion history. Don't need to open another pull request.

**Comment by DimitryW** [comment]
Well noted! thank you~

**Pull request closed without merging**
