### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by DimitryW**
吳佳俞
http://3.230.236.135:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
1. Layout will exceed screen width in small and middle screen size. (<1200px)
2. Your code will load first page twice if I do keyword search.

Fix them and leave comment for me to review again.

**Comment by DimitryW** [comment]
Noted, but I've tried many times to search keyword, it only shows first page once.
Could you advise which word you searched? I'll try to fix it.
Thank you. 
image

**Comment by cwpeng** [comment]
Try to check in network of developer tools, shown in my screenshot.

未命名-2

**Comment by DimitryW** [comment]
吳佳俞
I have revised and corrected my assignment. Kindly check, thank you!
http://3.230.236.135:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
